
spring:
    datasource:
        password: hahaschool
        url: jdbc:mysql://localhost:3306/cielo?charset=utf8mb4&serverTimezone=UTC
        username: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.SQLServer2012Dialect
        show-sql: true
#    mvc:
#      static-path-pattern: /**
#    resources:
#      static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
server:
  port: 46000
swagger:
  title: LinuxPerformanceMonitor
  description: The api doc for linux performance monitor
  contact:
    name: Cielo
    email: cielosun@outlook.com
    url: http://www.cnblogs.com/cielosun
net:
  totalBandWidth: 20