spring:
    datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        password: 123456
        url: jdbc:sqlserver://ecs.cielosun.info;databaseName=SpringBootTestDB
        username: sa
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.SQLServer2012Dialect
        show-sql: true
